apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2024-09-03T13:47:04Z"
  generation: 9
  labels:
    app: todo-prod-frontend
  name: todo-prod-frontend
  namespace: default
  resourceVersion: "7582793"
  uid: b44920a1-ed2d-46c9-8ed1-43674672c17d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-prod-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-prod-frontend
    spec:
      containers:
      - image: akscicd/todo-prod-frontend:v9
        imagePullPolicy: IfNotPresent
        name: todo-prod-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-06T11:02:27Z"
    lastUpdateTime: "2024-09-06T11:02:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-03T13:47:04Z"
    lastUpdateTime: "2024-09-06T13:10:51Z"
    message: ReplicaSet "todo-prod-frontend-749676cd64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
#----------------------------------------------------------------------
#load balancer service
#----------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-09-02T16:17:18Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: todo-prod-frontend
  name: todo-prod-frontend
  namespace: default
  resourceVersion: "5055379"
  uid: 3ea1bba5-8343-4b98-8b7c-7f53bdfcaba6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.239.29
  clusterIPs:
  - 34.118.239.29
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32201
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: todo-prod-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.93.221.41
