#-------------------------------------------------
#PV
#-------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-db-pv
  labels:
    name: todo-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: todo-db-disk
    fsType: ext4
  storageClassName: standard

---

#---------------------------------------------------
#PVC
#---------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-db-pvc
spec:
  accessModes:
    - ReadWriteOnce            # Sets the access mode to ReadWriteOnce.
  resources:
    requests:
      storage: 5Gi             # Requests 1 GiB of storage.
  selector:
    matchLabels:
      name: todo-db-pv
  storageClassName: standard
